# [START runtime]
runtime: nodejs10
handlers:
- url: /(.+\.js)
  static_files: peers/\1
  upload: peers/(.+\.js)

- url: /(.+\.css)
  static_files: peers/\1
  upload: peers/(.+\.css)

- url: /(.+\.png)
  static_files: peers/\1
  upload: peers/(.+\.png)

- url: /(.+\.jpg)
  static_files: peers/\1
  upload: peers/(.+\.jpg)

- url: /(.+\.svg)
  static_files: app/\1
  upload: peers/(.+\.svg)

- url: /favicon.ico
  static_files: peers/favicon.ico
  upload: peers/favicon.ico

- url: /(.+\.json)
  static_files: peers/\1
  upload: peers/(.+\.json)

- url: /(.+)
  static_files: peers/index.html
  upload: peers/index.html

- url: /
  static_files: peers/index.html
  upload: peers/index.html

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 1
# [END runtime]